### PR TITLE
File uploads array parsing

### PR DESCRIPTION
**Pull request by sshymko**
- Fix file uploads data structure to accommodate array form fields #2743
- Update file uploads data structure `$request->files` to match `$_FILES`
- Test file uploads data structure of different form field nesting levels
- Add Swoole logo to test fixture images

### CODE REVIEW

**Comment by sshymko** [comment]
All existing file upload tests and the the newly introduced test for array form fields upload pass.

**Comment by twose** [comment]
nice job but I don't know whether it will cause backward incompatibility

**Comment by sshymko** [comment]
@twose 
Yes, you're right the file uploads format changes for array form fields.
My arguments for accepting the changes:
- File uploads format is the same for flat form fields; it has changed only for arrays
- All existing file upload tests pass unmodified because they tested flat file uploads only
- File uploads format has never been documented, neither for flat nor array form fields
- Relying on undocumented functionality comes with backward-compatibility risks
- According to you and @matyhtf, array file uploads weren't supported (at least intentionally)

**Comment by sshymko** [comment]
@twose 
Introducing a setting is a good option except it would require to maintain both formats going forward.
Since the format is not documented and only matches `$_FILES` for flat form fields, probably not many projects rely on the behavior of array form fields.

**Comment by sshymko** [comment]
@twose 
Introduced setting `http_parse_files` disabled by default and covered both formats with tests.

**Comment by twose** [comment]
👍great job, it looks good

**Comment by twose** [comment]
How can I touch you online faster? Twitter?

**Pull request merged**
