### PR TITLE
on('beforehandshakeresponse') event

### PR DESCRIPTION
**Pull request by dmitryuk**
Fixes https://github.com/swoole/swoole-src/issues/4663

### CODE REVIEW

**Comment by NathanFreeman** [comment]
Hi @dmitryuk 
Would be also nice if you could add a new test.
Thanks.

**Comment by dmitryuk** [comment]
I have added the test, but didn't find a way how to check it locally. Please accept workflow

**Comment by dmitryuk** [comment]
I have checked the code in my project and it works as intended.

**Comment by dmitryuk** [comment]
@NathanFreeman What we'll do next? As I see test skipped since build timeout.

**Comment by NathanFreeman** [comment]
@dmitryuk 
Hi!
Sometime the build will timeout.
And next waiting for my team members to review it.
It's going to take some time.

**Comment by dmitryuk** [comment]
@matyhtf please review pr 🙏

**Comment by dmitryuk** [comment]
@matyhtf please approve the PR

**Comment by Appla** [comment]
I don't this this is a good approach.
Is possible to check user defined onhandshake' response to determine websocket extension options which handled by swoole internally?

**Comment by matyhtf** [comment]
I think both ways should be supported.

In some cases just to set a cookie or other http header, and do not want to re-implement the handshake, then we can use the beforeHandShakeResponse callback

**Comment by dmitryuk** [comment]
Hello. @matyhtf still waiting for release of the feature. Can you make a new tag with PR?

**Pull request merged**
