### PR TITLE
Implement HTTP method PURGE

### LINKED ISSUE #2462: Proposal: non-standard PURGE method support
Currently, Swoole does not support non-standard HTTP methods, such as PURGE used by Varnish.
Once supported, applications that already support Varnish cache invalidation could be configured to also send PURGE requests to a stateful Swoole web-server.

**Steps to reproduce:**
1. Implement an HTTP server:
    ```php
    $server = new \Swoole\Http\Server('127.0.0.1', 8080);
    $server->on('request', function ($request, $response) use ($server) {
        $response->header('Content-Type', 'text/plain');
        $response->end("Served by worker $server->worker_id\n");
    });
    $server->start();
    ```
2. Send HTTP request with a non-standard method:
    ```bash
    curl -X PURGE http://127.0.0.1:8080/
    ```

**Actual result:**
- PURGE request never reaches the request handling middleware:
    ```bash
    <h1>400 Bad Request</h1>
    ```

**Expected result:**
- PURGE request is served by the request handling middleware:
    ```bash
    Served by worker 0
    ```

### PR DESCRIPTION
**Pull request by sshymko**
- Parse PURGE method of proxy servers Nginx, Squid, Varnish
- Resolve #2462 Proposal: non-standard PURGE method support

### CODE REVIEW

**Comment by sshymko** [comment]
Non-standard HTTP method `PURGE` is supported by many proxy servers:
- [Nginx cache purge](https://docs.nginx.com/nginx/admin-guide/content-cache/content-caching/#purge_example)
- [Varish cache purge](https://varnish-cache.org/docs/3.0/tutorial/purging.html)
- [Squid cache purge](https://wiki.squid-cache.org/SquidFaq/OperatingSquid#How_can_I_purge_an_object_from_my_cache.3F)

Having Swoole support would allow it to mimic or proxy the above HTTP servers.

**Comment by sshymko** [comment]
@matyhtf 
I realize that the changes are targeting the 3rd party library shipped with the Swoole distribution. Please let me know where to contribute the changes if the direct PR to Swoole is not acceptable.

**Comment by matyhtf** [comment]
merged.

**Comment by sshymko** [comment]
@matyhtf 
Thanks you so much for accepting the changes! Really appreciate that!

**Pull request merged**
