### PR TITLE
Support LOB (value of type resource) for PostgreSQLStatement::execute()

### LINKED ISSUE #4810: Support for PDO Large Objects (LOBs) as stream resource
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

    ```php
    // example shown using Hyperf swoole-based framework
    $pdo = Db::connection('data2')->getPdo()->prepare(...);
    $stmt = $pdo->prepare("INSERT INTO table1 (column1, column2, binary3) VALUES ($1, $2, $3)");
    $stmt->bindParam('$3', $resource, \PDO::PARAM_LOB);

    // ...

    $streamResource = Db::connection('data2')->table('table1')->where('column1', $value)->pluck('binary3')->first();
    ```

    Trying to use INSERT and SELECT on binary columns which PDO usually treats as a stream resource https://www.php.net/manual/en/pdo.lobs.php

2. What did you expect to see?

    Ability to call PDOStatement `bindParam` with `PDO::PARAM_LOB`

4. What did you see instead?
`PHP Error:  Call to undefined method Swoole\Coroutine\PostgreSQLStatement::bindParam()`

5. What version of Swoole are you using (show your `php --ri swoole`)?
    ```
    swoole
        
    Swoole => enabled
    Author => Swoole Team <team@swoole.com>
    Version => 5.0.0
    Built => Aug 12 2022 23:57:16
    coroutine => enabled with boost asm context
    epoll => enabled
    eventfd => enabled
    signalfd => enabled
    cpu_affinity => enabled
    spinlock => enabled
    rwlock => enabled
    sockets => enabled
    openssl => OpenSSL 3.0.2 15 Mar 2022
    dtls => enabled
    http2 => enabled
    json => enabled
    curl-native => enabled
    pcre => enabled
    zlib => 1.2.11
    brotli => E16777225/D16777225
    mutex_timedlock => enabled
    pthread_barrier => enabled
    futex => enabled
    mysqlnd => enabled
    async_redis => enabled
    coroutine_postgresql => enabled
    
    Directive => Local Value => Master Value
    swoole.enable_coroutine => On => On
    swoole.enable_library => On => On
    swoole.enable_preemptive_scheduler => Off => Off
    swoole.display_errors => On => On
    swoole.use_shortname => On => On
    swoole.unixsock_buffer_size => 8388608 => 8388608
    ```

6. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
    - `uname -a`:
      - `Linux 4353894d-ea3c-47ed-8bda-63bfda6a0b59 4.4.0-1104-aws #109-Ubuntu SMP Tue May 10 11:27:41 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
    - `php -v`:
      - ```
        PHP 8.1.9 (cli) (built: Aug  4 2022 11:57:37) (NTS)
        Copyright (c) The PHP Group
        Zend Engine v4.1.9, Copyright (c) Zend Technologies
            with Zend OPcache v8.1.9, Copyright (c), by Zend Technologies```
    - `gcc -v`:
        ```
        Using built-in specs.
        COLLECT_GCC=gcc
        COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/11/lto-wrapper
        OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
        OFFLOAD_TARGET_DEFAULT=1
        Target: x86_64-linux-gnu
        Configured with: ../src/configure -v --with-pkgversion='Ubuntu 11.2.0-19ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-11/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-11 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-11-gBFGDP/gcc-11-11.2.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-11-gBFGDP/gcc-11-11.2.0/debian/tmp-gcn/usr --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-serialization=2
        Thread model: posix
        Supported LTO compression algorithms: zlib zstd
        gcc version 11.2.0 (Ubuntu 11.2.0-19ubuntu1)
        ```

### PR DESCRIPTION
**Pull request by Yurunsoft**
resolve #4810

### CODE REVIEW

**Comment by kingIZZZY** [comment]
Hey thanks for working on this!

Can you confirm whether this code actually takes advantage of performance with stream resource similar to PDO::PARAM_LOB, so that writing into the PDO database column and reading out of the PDO database column will in fact benefit from using stream resource? Ex. if a large binary file is written to and selected from a database column.

Or, is this implementation just a "patch / bridge" so that using PDO::PARAM_LOB does not break and still works, but it does not actually benefit from streaming resource from/to the database server? It just reads the entire stream into a string?

Does the core PHP implementation of PDO LOBs use any special RDBMS APIs in order to have performant streaming of large binary data to-and-from the database? If yes - Can Swoole\Coroutine\PostgreSQL also do that?

Thank you 🙏

**Comment by Yurunsoft** [comment]
pdo_pgsql supports stream resource and pgsql Large-object.
This pr only implements stream resource.
I'll try to implement pgsql Large-object in swoole later.

**Comment by kingIZZZY** [comment]
🙏 Ok great!

Just for reference (I don't really know about all this... just hoping it's correct) I think what I was asking about it something like these:
- https://github.com/php/php-src/blob/master/ext/pdo_pgsql/pgsql_driver.c
- [Write LOB `lo_write()`](https://github.com/php/php-src/blob/master/ext/pdo_pgsql/pgsql_driver.c#L130)
- [Read LOB `lo_read()`](https://github.com/php/php-src/blob/master/ext/pdo_pgsql/pgsql_driver.c#L136)
- [PostgreSQL Client Interfaces Chapter 35. Large Objects](https://www.postgresql.org/docs/14/lo-interfaces.html#LO-WRITE)

Thanks again for your efforts on this feature!

**Comment by kingIZZZY** [comment]
Thank you @Yurunsoft ! 🙌

I see Hyperf builds are failing - I was personally trying to use this feature in Hyperf... should I try building it anyway? Or should I wait for other fixes so Hyperf will build

**Comment by Yurunsoft** [comment]
> Thank you @Yurunsoft ! 🙌
> 
> I see Hyperf builds are failing - I was personally trying to use this feature in Hyperf... should I try building it anyway? Or should I wait for other fixes so Hyperf will build

The fact that the hyperf test did not pass has nothing to do with this PR, you can create an issue for hyperf

**Comment by kingIZZZY** [comment]
Ahhhh ok thanks for clarifying that 👍

**Pull request merged**
