### PR TITLE
Fix support of unicode URI path

### LINKED ISSUE #2751: Special characters in URI corrupt request object
**Preconditions:**
- Swoole 4.x (any version)

**Steps to reproduce:**
1. Create a simple Swoole server that responds with request debug information:
    ```php
    $server = new \Swoole\Http\Server('127.0.0.1', 8180);
    $server->on('request', function ($request, $response) {
        $response->header('Content-Type', 'text/plain');
        $debug = [
            'server' => $request->server,
            'headers' => $request->header,
        ];
        $response->end(var_export($debug, true));
    });
    $server->start();
    ```
2. Send request with special characters in headers:
    ```bash
    curl 'http://127.0.0.1:8180/test' \
        -H 'X-Test-Header: test™'
    ```
3. Send request with special characters in both URI and headers:
    ```bash
    curl 'http://127.0.0.1:8180/test™' \
        -H 'X-Test-Header: test™'
    ```

**Expected result:**
- Swoole parses request data with special characters in headers
- Swoole parses request data with special characters in URI
- Special characters are available in request object:
    ```php
    array (
      'server' => 
      array (
        'request_method' => 'GET',
        'request_uri' => '/test™',
        'path_info' => '/test™',
        'request_time' => 1565292046,
        'request_time_float' => 1565292047.800587,
        'server_port' => 8180,
        'remote_port' => 55166,
        'remote_addr' => '127.0.0.1',
        'master_time' => 1565292046,
        'server_protocol' => 'HTTP/1.1',
      ),
      'headers' => 
      array (
        'host' => '127.0.0.1:8180',
        'user-agent' => 'curl/7.61.1',
        'accept' => '*/*',
        'x-test-header' => 'test™',
      ),
    )
    ```

**Actual result:**
- Swoole parses request data with special characters in headers
- Swoole DOES NOT support special characters in URI
- Special characters in URI corrupt request object:
    ```php
    array (
      'server' => 
      array (
        'request_method' => 'GET',
        'request_uri' => '',
        'path_info' => '',
        'request_time' => 1565292054,
        'request_time_float' => 1565292055.176415,
        'server_port' => 8180,
        'remote_port' => 55168,
        'remote_addr' => '127.0.0.1',
        'master_time' => 1565292054,
        'server_protocol' => 'HTTP/1.0',
      ),
      'headers' => 
      array (
      ),
    )
    ```
    Notice empty `request_uri`, `path_info`, `headers` and protocol HTTP/1.0 instead of HTTP/1.1.

### PR DESCRIPTION
**Pull request by sshymko**
- Remove strict validation of URI path characters
- Resolve #2751 Special characters in URI corrupt request object

### CODE REVIEW

**Comment by sshymko** [comment]
@matyhtf 
I realize that the changes are targeting the 3rd party library shipped with the Swoole distribution. Please let me know where to contribute the changes if the direct PR to Swoole is not acceptable.

**Comment by twose** [comment]
I am afraid that it's not right, obviously these code are useful, but you just removed them
the right way is to compare source with http-parser of PHP

**Comment by sshymko** [comment]
@twose 
Yeah, unfortunately I'm not proficient in C to implement a proper multi-byte character encoding.
I'm afraid trying to match Swoole HTTP parser with other implementations (such as Nginx) would result into complete rewrite of HTTP protocol interpretation by Swoole.

**Comment by sshymko** [comment]
@twose @matyhtf 
Would you be able to use [lemire/fastvalidate-utf-8](https://github.com/lemire/fastvalidate-utf-8) for unicode validation?

**Comment by matyhtf** [comment]
From twosee:

we need to upgrade http parser with https://github.com/nodejs/http-parser/blob/master/http_parser.c

maybe set HTTP_PARSER_STRICT to 0 can solve this problem

but anyway, it should be encoded as the browser does

**Comment by sshymko** [comment]
@matyhtf 
Yes, you're correct, URI is expected to be encoded. The thing is that other HTTP servers, such as Nginx, do handle unencoded unicode URI successfully. Would be great for Swoole to do the same.

**Pull request closed without merging**
