### PR TITLE
fix document_root can't be a relative path

### PR DESCRIPTION
**Pull request by windrunner414**

### CODE REVIEW

**Comment by twose** [comment]
为什么需要支持这个?

**Comment by windrunner414** [comment]
@twose 一般来说没有用
#2323

**Comment by windrunner414** [comment]
cc @woody712
Are there any situations you need to use relative path?

**Comment by windrunner414** [comment]
cc @woody712
Are there any situations you need to use relative path?

**Comment by windrunner414** [comment]
cc @twose

**Pull request merged**
